### ISSUE TITLE
use gradle to build:xmldumper appear error

### ISSUE THREAD

**Issue by weifang-cool** [google/android-uiconductor#81]
Hi there~
when I follow the guide to build xmldumper,use command: gradle wrapper assembleDebug
appear follow error:
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'xmldumper'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:4.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:4.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.1/gradle-4.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.1/gradle-4.0.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
`

I hava install gradle 6.5,
`------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Linux 4.15.0-123-generic amd64
`
is default gradle config not correct?I can't find distributionUrl config.
Thanks

**Comment by weifang-cool** [comment]
after google ,i realise  that this problem may caused by JDK version not correct.
and resolve this problem by use Android Studio compile xmldumper app.

**Comment by heyuchen** [comment]
You can use the prebuild XMLdumper apk as well.
